// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Learning_EFCore.Database
{
    public partial class ArticleCategory
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int Sort { get; set; }
        public string Summary { get; set; }
    }
}